services:
  marqo:
    image: marqoai/marqo:latest
    container_name: marqo
    ports:
      - "8882:8882"
    environment:
      - MARQO_ENABLE_BATCH_APIS=true
    volumes:
      - ./.marqo_cache:/app/src/marqo/cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8882/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - app_network

  rails_app:
    image: document-store-mcp
    container_name: document-store-mcp-rails
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8347:80"
    environment:
      - RAILS_ENV=production
      - SOLID_QUEUE_IN_PUMA=true
      - SECRET_KEY_BASE=1
      - MARQO_URL=http://marqo:8882
    depends_on:
      marqo:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./db:/rails/db
      - ./storage:/rails/storage
      - ./public/documents:/rails/public/documents

networks:
  app_network:
    driver: bridge

volumes:
  marqo_data:
